[theme]
base = "light"
primaryColor = "#F04348"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FB"
textColor = "#090C12"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
